name: Azazeo
favicon: null
layout_spectrum: 0.41197
typography_spectrum: 1
title: Блог интернет-пользователя Azazeo
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-71584406-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffffd'
    - '#ab7a11'
    - '#16050b'
    - '#ff2314'
    - '#0fff4e'
  brandStrength: 0.125
  lightness: 0.75
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
