name: Azazeo
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: Блог интернет-пользователя Azazeo
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-71584406-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3d0000'
    - '#443e3e'
    - '#fff2ed'
    - '#8ea59b'
    - '#dfaf05'
  brandStrength: 0.125
  lightness: 0.75
  saturation: 0.0625
  rhythmicContrast: 1
purpose: []
