name: Azazeo
favicon: null
layout_spectrum: 0.87551
typography_spectrum: 0.19188
title: "Azazeo's blog"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-71584406-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#98e27f'
    - '#557689'
    - '#cfeaff'
    - '#84c1f8'
    - '#6ab0a2'
  brandStrength: 0
  lightness: 0.75
  saturation: 0
  rhythmicContrast: 1
purpose: []
