name: Azazeo
favicon: null
layout_spectrum: 0.22902
typography_spectrum: 1
title: "Azazeo's blog"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-71584406-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#111a21'
    - '#e7bd00'
    - '#7e4976'
    - '#5d83ab'
    - '#ffff88'
  brandStrength: 0
  lightness: 0.75
  saturation: 0.25
  rhythmicContrast: 1
purpose: []
